version: "3"
services:
  jupytepide-hub:
    # build an image with SwarmSpawner and our jupyterhub_config.py
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    image: "jupytepide/hub"
    container_name: jupytepide-hub
    # mount the docker socket
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - ./jupyterhub_config.py:/tmp/jupyterhub_config.py
    - ./run-from-compose.sh:/run-from-compose.sh
    - /opt/data/priv/:/opt/data/priv/
    networks:
    - jupyterhub-net
    # This is necessary to prevent the singleton hub from using its service number as its hostname
    ports:
    - "8000:8000"
    hostname: jupytepide-hub
    environment:
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      DOCKER_SPAWN_NOTEBOOK_IMAGE: ${DOCKER_SPAWN_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      SPAWN_USER: ${SPAWN_USER}
    command: sh /run-from-compose.sh

  nginx:
    env_file: .env
    image: linuxserver/letsencrypt
    container_name: nginx
    hostname: nginx
    networks:
    - jupyterhub-net
    # expose the proxy to the world
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "nginx_volume:/config"
    - /home/eouser/jupytep-dev/swarm/letsencrypt_container_nginx.conf:/config/nginx/site-confs/default
    environment:
      EMAIL: ${EMAIL}
      URL: ${URL}
    cap_add:
    - NET_ADMIN

  postgis:
    image: kartoza/postgis:9.6-2.4
    container_name: jupytepide-postgis
    networks:
    - jupyterhub-net
    volumes:
    - postgis-db-data:/var/lib/postgresql
    ports:
    - "25432:5432"
    env_file:
    - postgis.env
    restart: on-failure
    healthcheck:
      test: "exit 0"

  geoserver:
    image: jupytepide/geoserver:2.13.0-1.0
    container_name: jupytepide-geoserver
    networks:
    - jupyterhub-net
    volumes:
    - geoserver-data:/opt/geoserver/data_dir
    ports:
    - "8090:8080"
    restart: on-failure
    env_file:
    - geoserver.env
    #    depends_on:
    #      postgis:
    #        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  mapnik:
    image: "jupytepide/mapnik-flask:1.2"
    container_name: jupytepide-mapnik
    networks:
    - jupyterhub-net
    ports:
    - "9443:443"
    volumes:
    - /opt/pub/mapnik:/opt/mapnik

  pywps:
    image: "pywps/flask-ubuntu:16.0.4"
    container_name: jupytepide-pywps
    networks:
    - jupyterhub-net
    ports:
    - "5000:5000"

networks:
  jupyterhub-net:
    external:
      name: jupytepide-swarm-net

volumes:
  db:
    external:
      name: ${DB_VOLUME_DATA}
  nginx_volume:
    external:
      name: ${NGINX_VOLUME_DATA}
  geoserver-data:
    external:
      name: ${GEOSERVER_VOLUME_DATA}
  postgis-db-data:
    external:
      name: ${POSTGIS_VOLUME_DATA}